import 'dart:convert';
import 'dart:io';
import 'package:flutter/material.dart';
import 'package:flutter_svg/flutter_svg.dart';
import 'package:path_provider/path_provider.dart';
import 'package:path/path.dart' as p;
import 'musicxml_types.dart';

/// A MusicXML renderer for Linux that uses the MuseScore (mscore) CLI.
/// 
/// This provides high-quality, professional-grade rendering on Linux
/// where WebView support is limited.
class MusicXmlMscoreRenderer extends StatefulWidget {
  final String musicXml;
  final MusicXmlRenderOptions options;
  final OnScoreLoaded? onLoaded;
  final Color backgroundColor;

  const MusicXmlMscoreRenderer({
    super.key,
    required this.musicXml,
    required this.options,
    this.onLoaded,
    this.backgroundColor = Colors.white,
  });

  @override
  State<MusicXmlMscoreRenderer> createState() => _MusicXmlMscoreRendererState();
}

class _MusicXmlMscoreRendererState extends State<MusicXmlMscoreRenderer> {
  List<File> _svgFiles = [];
  bool _isLoading = true;
  String? _error;
  Directory? _tempDir;

  @override
  void initState() {
    super.initState();
    _render();
  }

  @override
  void didUpdateWidget(MusicXmlMscoreRenderer oldWidget) {
    super.didUpdateWidget(oldWidget);
    if (oldWidget.musicXml != widget.musicXml) {
      _render();
    }
  }

  @override
  void dispose() {
    _cleanup();
    super.dispose();
  }

  Future<void> _cleanup() async {
    if (_tempDir != null && _tempDir!.existsSync()) {
      try {
        await _tempDir!.delete(recursive: true);
      } catch (e) {
        debugPrint('Failed to cleanup temp dir: $e');
      }
    }
  }

  Future<void> _render() async {
    setState(() {
      _isLoading = true;
      _error = null;
    });

    try {
      final baseDir = await getTemporaryDirectory();
      _tempDir = await baseDir.createTemp('borge_mscore_');
      
      final mxmlFile = File(p.join(_tempDir!.path, 'score.musicxml'));
      
      // Check if it's base64 (likely for .mxl files)
      bool isBase64 = !widget.musicXml.trim().startsWith('<');
      
      if (isBase64) {
        try {
          final bytes = base64Decode(widget.musicXml.replaceAll(RegExp(r'\s+'), ''));
          await mxmlFile.writeAsBytes(bytes);
        } catch (e) {
          // If decoding fails, fallback to writing as string
          await mxmlFile.writeAsString(widget.musicXml);
        }
      } else {
        await mxmlFile.writeAsString(widget.musicXml);
      }

      final svgBaseName = p.join(_tempDir!.path, 'page');
      
      // Run MuseScore
      // Note: MuseScore 2 saves files as page-1.svg, page-2.svg, etc.
      final result = await Process.run('mscore', [
        mxmlFile.path,
        '-o',
        '$svgBaseName.svg',
      ]);

      if (result.exitCode != 0) {
        throw Exception('MuseScore failed with exit code ${result.exitCode}: ${result.stderr}');
      }

      // Find all generated SVGs
      final files = _tempDir!
          .listSync()
          .whereType<File>()
          .where((f) => f.path.endsWith('.svg'))
          .toList();
      
      // Sort files numerically by page number
      files.sort((a, b) {
        final regExp = RegExp(r'page-(\d+)\.svg');
        final matchA = regExp.firstMatch(a.path);
        final matchB = regExp.firstMatch(b.path);
        if (matchA != null && matchB != null) {
          return int.parse(matchA.group(1)!).compareTo(int.parse(matchB.group(1)!));
        }
        return a.path.compareTo(b.path);
      });

      if (files.isEmpty) {
        throw Exception('No SVG files were generated by MuseScore');
      }

      setState(() {
        _svgFiles = files;
        _isLoading = false;
      });

      // Notify loaded
      widget.onLoaded?.call(MusicXmlScoreInfo(
        title: 'Score (MuseScore View)',
        pageCount: files.length,
      ));

    } catch (e) {
      debugPrint('Mscore renderer error: $e');
      setState(() {
        _error = e.toString();
        _isLoading = false;
      });
    }
  }

  @override
  Widget build(BuildContext context) {
    if (_isLoading) {
      return Center(
        child: Column(
          mainAxisSize: MainAxisSize.min,
          children: [
            const CircularProgressIndicator(),
            const SizedBox(height: 16),
            const Text('Engraving with MuseScore...'),
          ],
        ),
      );
    }

    if (_error != null) {
      return Center(
        child: Padding(
          padding: const EdgeInsets.all(16.0),
          child: Column(
            mainAxisSize: MainAxisSize.min,
            children: [
              const Icon(Icons.error_outline, color: Colors.red, size: 48),
              const SizedBox(height: 16),
              Text('Rendering Error', style: Theme.of(context).textTheme.titleLarge),
              const SizedBox(height: 8),
              Text(_error!, textAlign: TextAlign.center),
              const SizedBox(height: 16),
              ElevatedButton(onPressed: _render, child: const Text('Retry')),
            ],
          ),
        ),
      );
    }

    // Since our viewer handles one page at a time, we only show the requested page
    final pageIndex = widget.options.initialPage ?? 0;
    final displayIndex = pageIndex.clamp(0, _svgFiles.length - 1);

    return Container(
      color: widget.backgroundColor,
      child: SvgPicture.file(
        _svgFiles[displayIndex],
        fit: BoxFit.contain,
        placeholderBuilder: (context) => const Center(child: CircularProgressIndicator()),
      ),
    );
  }
}
