#!/bin/bash

echo "=== Google OAuth Test User Setup ==="
echo ""
echo "You're seeing 'Access Blocked' because your app is in Testing mode"
echo "and you haven't been added as a test user yet."
echo ""
echo "To fix this:"
echo ""
echo "1. Visit the OAuth consent screen configuration:"
echo "   https://console.cloud.google.com/apis/credentials/consent?project=borge-music-viewer"
echo ""
echo "2. Scroll down to 'Test users' section"
echo ""
echo "3. Click 'ADD USERS'"
echo ""
echo "4. Enter your email address: lesser.evil@gmail.com"
echo ""
echo "5. Click 'SAVE'"
echo ""
echo "6. Try signing in again on your device"
echo ""
echo "Note: While your app is in 'Testing' publishing status, only test users"
echo "can access it. This is perfect for development - you don't need to go"
echo "through Google's verification process!"
echo ""
echo "Alternative: You can also set the app to 'Internal' if you have a"
echo "Google Workspace account, which allows all users in your organization."
echo ""
